# Run static checks
name: lint
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Set up Go so that golangci-lint has the right $GOROOT and can find
      # the right standard libraries. See:
      # https://github.com/reviewdog/action-golangci-lint/issues/73#issuecomment-813386935
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: golangci/golangci-lint-action@v4.0.0
        with:
          args: --verbose --timeout=3m
